### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by peat80** [LS80/script.libreelec.devupdater#6]
I've translated this addon in German.

[German.zip](https://github.com/LS80/script.libreelec.devupdater/files/1346029/German.zip)

**Comment by ManuStrozor** [comment]
Can you make a pull request ?

**Comment by peat80** [comment]
I've got no idea how to do that.

**Comment by ManuStrozor** [comment]
Just have to Fork the project and commit some modifications before the pull request

**Comment by LS80** [comment]
@peat80 Thanks I'll add this.
